### PR TITLE
Added alternative Scss parser with Compass framework support

### PR DESCRIPTION
**Pull request by mervick**

### CODE REVIEW

**Comment by nizsheanez** [comment]
As i see you replaced Sass, why?

**Comment by mervick** [comment]
Sass parser does not support the integration of Compass framefork out of the box, unlike the new Scss which uses `leafo/scssphp-compass` library

**Comment by mervick** [comment]
By the way, I did not touch Sass parser, I just added the alternative, and changed to use it in default config

**Comment by nizsheanez** [comment]
is it backward compatible change?

**Comment by mervick** [comment]
Now it backward compatible.

**Pull request merged**
